const sampleCourtFeeData=[
  { caseId: "C001", partyName: "Rahul Sharma", feeType: "Filing Fee", amount: 500, status: "Paid" },
  { caseId: "C002", partyName: "Neha Verma", feeType: "Certified Copy", amount: 200, status: "Pending" },
  { caseId: "C003", partyName: "Amit Singh", feeType: "Processing Fee", amount: 350, status: "Paid" },
  { caseId: "C004", partyName: "Priya Yadav", feeType: "Hearing Fee", amount: 600, status: "Pending" },
  { caseId: "C005", partyName: "Vikas Gupta", feeType: "Filing Fee", amount: 500, status: "Paid" },
  { caseId: "C006", partyName: "Sonia Mehra", feeType: "Certified Copy", amount: 250, status: "Paid" },
  { caseId: "C007", partyName: "Anil Kumar", feeType: "Service Fee", amount: 400, status: "Pending" },
  { caseId: "C008", partyName: "Ritu Raj", feeType: "Filing Fee", amount: 550, status: "Paid" },
  { caseId: "C009", partyName: "Deepak Chauhan", feeType: "Hearing Fee", amount: 650, status: "Paid" },
  { caseId: "C010", partyName: "Pooja Sinha", feeType: "Certified Copy", amount: 300, status: "Pending" },
  { caseId: "C011", partyName: "Nitesh Patel", feeType: "Processing Fee", amount: 450, status: "Paid" },
  { caseId: "C012", partyName: "Rakesh Joshi", feeType: "Filing Fee", amount: 520, status: "Pending" },
  { caseId: "C013", partyName: "Shalini Agarwal", feeType: "Service Fee", amount: 380, status: "Paid" },
  { caseId: "C014", partyName: "Vivek Tiwari", feeType: "Hearing Fee", amount: 700, status: "Pending" },
  { caseId: "C015", partyName: "Monika Das", feeType: "Certified Copy", amount: 230, status: "Paid" },
  { caseId: "C016", partyName: "Saurabh Mishra", feeType: "Filing Fee", amount: 500, status: "Paid" },
  { caseId: "C017", partyName: "Kiran Bhatia", feeType: "Hearing Fee", amount: 640, status: "Pending" },
  { caseId: "C018", partyName: "Rohit Pandey", feeType: "Processing Fee", amount: 410, status: "Paid" },
  { caseId: "C019", partyName: "Ananya Sen", feeType: "Service Fee", amount: 390, status: "Pending" },
  { caseId: "C020", partyName: "Manoj Kaushik", feeType: "Certified Copy", amount: 280, status: "Paid" },
  { caseId: "C021", partyName: "Sneha Kapoor", feeType: "Filing Fee", amount: 500, status: "Paid" },
  { caseId: "C022", partyName: "Ashish Jain", feeType: "Hearing Fee", amount: 620, status: "Pending" },
  { caseId: "C023", partyName: "Divya Rani", feeType: "Service Fee", amount: 350, status: "Paid" },
  { caseId: "C024", partyName: "Rajeev Sinha", feeType: "Certified Copy", amount: 260, status: "Pending" },
  { caseId: "C025", partyName: "Kavita Mehta", feeType: "Filing Fee", amount: 520, status: "Paid" },
  { caseId: "C026", partyName: "Harshit Goyal", feeType: "Hearing Fee", amount: 610, status: "Paid" },
  { caseId: "C027", partyName: "Rachna Chawla", feeType: "Processing Fee", amount: 440, status: "Pending" },
  { caseId: "C028", partyName: "Gaurav Thakur", feeType: "Certified Copy", amount: 270, status: "Paid" },
  { caseId: "C029", partyName: "Simran Kaur", feeType: "Filing Fee", amount: 500, status: "Pending" },
  { caseId: "C030", partyName: "Aman Raj", feeType: "Hearing Fee", amount: 650, status: "Paid" }
]

module.exports={Feedata:sampleCourtFeeData}